<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>area_Page No 8_24</name>
   <tag></tag>
   <elementGuidId>e31cb1b8-cd4b-4272-b99f-3d7a55de087f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#24</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//area[@id='24']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\32 4&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>area</value>
      <webElementGuid>0e934342-be6d-452d-aef6-8eee99262ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>36251d06-1b0d-4d7e-a569-167fc77f66f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>88921b32-36fa-4106-98f6-aac4d3ac8770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>coords</name>
      <type>Main</type>
      <value>203,845,495,973</value>
      <webElementGuid>60e1afed-63d4-4b90-b9b5-aea134aff44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>be55a995-289c-47dc-8599-4981a3d08e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>lahore/2025-09-10/page-1/detail-24</value>
      <webElementGuid>84c7a4cb-3bb4-428b-b7c8-a07faa1b4bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showDetail(this)</value>
      <webElementGuid>2ee81f5f-dc93-4aac-8bc1-b206145a6506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;24&quot;)</value>
      <webElementGuid>8690657d-9b8b-46fe-a898-ffa9e1b60429</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//area[@id='24']</value>
      <webElementGuid>fdde606c-1ed5-4e18-98e3-df135a4d4acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//map[@id='pagemap']/area[25]</value>
      <webElementGuid>9b56c615-8462-41f0-9818-3796edd00c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//area[25]</value>
      <webElementGuid>69523bda-1c60-419d-a9f0-bfa8009b55db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//area[@id = '24' and @href = 'javascript:void(0)']</value>
      <webElementGuid>e2ad0213-075c-419b-ba8d-98f90d339fdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
