<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>f3ee7ccf-aa70-4518-9b2c-2b12f189e736</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Jameel_font&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='jameel-font-checker-icon']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Jameel_font&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>846f9d18-e4db-43aa-b69d-cb5986fad0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dailypakistan.com.pk/assets/dailypakistan/images/urdu-fownload-font.png</value>
      <webElementGuid>8a3cfca9-e595-4a61-b879-347b5fc921b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>ac5aade1-2272-4605-aee5-0c90a045cd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>92e44eae-20ff-4a9c-8254-baf732561da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Jameel_font</value>
      <webElementGuid>819c071e-b726-4118-9e97-5d5c67060ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jameel-font-checker-icon&quot;)/a[@class=&quot;home-menu-item&quot;]/img[1]</value>
      <webElementGuid>9cfdfda4-1937-4615-80df-bd4fc2494423</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='jameel-font-checker-icon']/a/img</value>
      <webElementGuid>333ce547-bbc1-4789-ae68-a6abca2436e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Jameel_font']</value>
      <webElementGuid>23353feb-5ad3-41fb-a265-dc54cce9f4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/img</value>
      <webElementGuid>f1b95370-54c1-4be1-9d9d-a1206c1dedc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dailypakistan.com.pk/assets/dailypakistan/images/urdu-fownload-font.png' and @alt = 'Jameel_font']</value>
      <webElementGuid>a525cb42-7f8e-4ac1-b082-0791a750d8ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
